### ISSUE TITLE
Feedback: Sockets 2017

### ISSUE THREAD

**Issue by rolandweber** [rolandweber/pityoulish#57]
I split the classroom exercise in two parts, with a block of theory inbetween. I still dedicated a full session of 2:30 h on the exercise, and not everybody got through. Still, it felt better and more structured than last year.

Student feedback at the end of the session:
- 2 positive, it's good to see code that relates to the diagrams from the blackboard, and to the abstraction layers I explained
- 1 negative, way too much time is spent on something that could have been explained in a few minutes

Timeline of the classroom session:
1. Repetition of socket addresses. Distinction between server sockets and client sockets when connecting.
2. Debugging, part 1: fix the first problem (connect), continue until the second
3. Theory. Three layers of abstraction: application (high-level functionality), TLVs (encoding and parsing of messages), binary connection (network transport). Server-side JavaDocs of the respective classes.
4. Debugging, part 2: fix the remaining problems (parse TLV, build TLV, implement request)

42 minutes for part 1, about 80% of students had fixed the first problem by then. They could continue during the break. 40 minutes for part 2, then de-briefing for the last ten minutes of the class. Again with the option to continue, but not everybody had completed the exercise by the end of the class.

Nobody explicitly stopped when running into the second problem to fix. They just continued, of course. The faster programmers finished early and got bored. I should find something for them to do next year. Maybe an actual programming task, like writing a client that executes a series of requests (obtain ticket, put message, return ticket).

Other problems observed or reported:
- Confusion about different ports for the web server and message board server on the same machine.
- Confusion about `bind` vs. `connect`. The former is known from the Tutorial.
- Questions about the meaning of the "marker".
- IDE problems.
- Network problems.
- Too much text.
- Unclear distinction between parts 1 and 2.

Ideas for next year:
- Before the exercise, discuss high-level functionality of the Message Board. The roles of markers should be clear.
- Before the exercise, discuss basic socket operations (C API) briefly. The roles of `bind` and `connect` should be clear.
- Write both ports (HTTP, Message Board) on the board.

- [x] Improve the Tutorial to sort out IDE problems in advance. See #56.
- [x] Rephrase "Then stop to think." somewhere in the instructions. It might be misunderstood.
- [x] Refactor the instructions, see #64. I've switched from a self-learning exercise with instructor assistance to a guided exercise. This probably requires a different set of instructions. Maybe keep both in parallel.
- [ ] Add a picture or table for the three layers of abstraction to the instructor's notes. With classnames, preferably linked to the JavaDocs. Point out the layers of abstraction in the code overview of the exercise too, see #58.
